// <auto-generated />
namespace FreeLance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class approvebycoordinatornull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(approvebycoordinatornull));
        
        string IMigrationMetadata.Id
        {
            get { return "201511011628178_approve-by-coordinator-null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
